#!/bin/bash

set -e

ENVIRONMENT=DEV

MOBILE_STS_DEV_STS_BASE_URL=https://token.dev.account.gov.uk
MOBILE_STS_DEV_ORCHESTRATION_BASE_URL=https://auth-stub.mobile.dev.account.gov.uk
MOBILE_STS_DEV_MOCK_EXTERNAL_CRI_BASE_URL=https://mock-issuer.token.dev.account.gov.uk
MOBILE_STS_DEV_STS_MOCK_CLIENT_BASE_URL=https://mock-client.token.dev.account.gov.uk
MOBILE_STS_DEV_MOCK_CLIENT_ID=bCAOfDdDSwO4ug2ZNNU1EZrlGrg
MOBILE_STS_DEV_REDIRECT_URI=https://mobile.dev.account.gov.uk/redirect

DATA_FILE_PATH=data
LOG_OUTPUT_FILE=sts-reauthentication-test-data-$ENVIRONMENT-temp.txt
DATA_FILE_NAME=sts-reauthentication-test-data-$ENVIRONMENT.json

rm -f $DATA_FILE_PATH/$LOG_OUTPUT_FILE && mkdir -p $DATA_FILE_PATH && touch $DATA_FILE_PATH/$LOG_OUTPUT_FILE \
    && npm start && k6 run ../../dist/mobile/sts.js -e PROFILE=smoke -e SCENARIO=generateReauthenticationTestData \
    -e EXECUTION_CREDENTIALS="$1" \
    -e MOBILE_STS_DEV_STS_BASE_URL=$MOBILE_STS_DEV_STS_BASE_URL \
    -e MOBILE_STS_DEV_STS_MOCK_CLIENT_BASE_URL=$MOBILE_STS_DEV_STS_MOCK_CLIENT_BASE_URL \
    -e MOBILE_STS_DEV_MOCK_EXTERNAL_CRI_BASE_URL=$MOBILE_STS_DEV_MOCK_EXTERNAL_CRI_BASE_URL \
    -e MOBILE_STS_DEV_ORCHESTRATION_BASE_URL=$MOBILE_STS_DEV_ORCHESTRATION_BASE_URL \
    -e MOBILE_STS_DEV_MOCK_CLIENT_ID=$MOBILE_STS_DEV_MOCK_CLIENT_ID \
    -e MOBILE_STS_DEV_REDIRECT_URI=$MOBILE_STS_DEV_REDIRECT_URI \
    -e MOBILE_STS_BUILD_STS_BASE_URL=$MOBILE_STS_BUILD_STS_BASE_URL \
    -e MOBILE_STS_BUILD_STS_MOCK_CLIENT_BASE_URL=$MOBILE_STS_BUILD_STS_MOCK_CLIENT_BASE_URL \
    -e MOBILE_STS_BUILD_MOCK_EXTERNAL_CRI_BASE_URL=$MOBILE_STS_BUILD_MOCK_EXTERNAL_CRI_BASE_URL \
    -e MOBILE_STS_BUILD_ORCHESTRATION_BASE_URL=$MOBILE_STS_BUILD_ORCHESTRATION_BASE_URL \
    -e MOBILE_STS_BUILD_MOCK_CLIENT_ID=$MOBILE_STS_BUILD_MOCK_CLIENT_ID \
    -e MOBILE_STS_BUILD_REDIRECT_URI=$MOBILE_STS_BUILD_REDIRECT_URI \
    -e ENVIRONMENT=$ENVIRONMENT -e AWS_REGION=eu-west-2 \
    --log-format json --log-output=file=./$DATA_FILE_PATH/$LOG_OUTPUT_FILE

rm -f $DATA_FILE_PATH/$DATA_FILE_NAME

jq -rc 'select(
  .level=="info"
  and .source=="console"
  and (.msg | contains("Load Profile: ")|not)
  and (.msg | contains("Scenarios: ")|not))
  |
  .msg
' $DATA_FILE_PATH/$LOG_OUTPUT_FILE | jq -s > $DATA_FILE_PATH/$DATA_FILE_NAME

rm -f $DATA_FILE_PATH/$LOG_OUTPUT_FILE