name: Publish TypeDoc Documentation

on:
  push:
    branches:
      - main
    paths:
      - "deploy/scripts/src/common/utils/**"

defaults:
  run:
    shell: bash
    working-directory: ./deploy/scripts

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup nodeJS v20
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: "deploy/scripts/package-lock.json"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Create TypeDoc documentation
        run: npx typedoc ./src/common/utils/**/*.ts

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: deploy/scripts/docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
